### PR TITLE
Add a UI to select the aggregation function of a field

### PR DESCRIPTION
**Pull request by ValentinH**
As discussed in #10.

The list of selectable functions is set using the `aggregates` option of the config.

The default value is: 

``` js
[
      {name: 'count', caption: 'Count', aggregateFunc: Aggregations.count},
      {name: 'sum', caption: 'Sum', aggregateFunc: Aggregations.sum},
      {name: 'avg', caption: 'Average', aggregateFunc: Aggregations.avg},
      {name: 'min', caption: 'Minimum', aggregateFunc: Aggregations.min},
      {name: 'max', caption: 'Maximum', aggregateFunc: Aggregations.max},
      {name: 'prod', caption: 'Product', aggregateFunc: Aggregations.prod},
      {name: 'stdev', caption: 'Standard Deviation', aggregateFunc: Aggregations.stdev},
      {name: 'stdevp', caption: 'Standard Deviation P.', aggregateFunc: Aggregations.stdevp},
      {name: 'var', caption: 'Variance', aggregateFunc: Aggregations.var},
      {name: 'varp', caption: 'Variance P.', aggregateFunc: Aggregations.varp}
]
```
- `name` is used to be displayed in the field like: "Field Caption (avg)"
- `caption` is used to be displayed in the select field.
- `aggregateFunc` works like the `aggregateFunc` option of the Pivot Grid Field: it can either be a constant such as 'avg' or 'max' or a function.

### CODE REVIEW

**Comment by nnajm** [comment]
Hi Valentin,

Really good start. But, imo, it's not complete. My observations:
- the code for this popup and the filter popup can be combined (using mixins)
- config aggregates should extend default ones, not replace them.
- no need to rebuild the entire pivot grid, just recompute that field values and refresh the data area
- aggregate name should be highlighted when hovered
- popup is not aligned with anything and its style is different from the filter popup (all popups should have the same style)

Thanks,

--  
nnajm.

**Comment by ValentinH** [comment]
> - the code for this popup and the filter popup can be combined (using mixins)

I think we should diretly merge filters and aggregates in a common settings popup (like you mention in #10)

> - config aggregates should extend default ones, not replace them.

I am not sure to understand what you mean. I added an default array in the aggregate module to add caption field for the aggregates (for the select widget).

> - no need to rebuild the entire pivot grid, just recompute that field values and refresh the data area.

About the rebuilding part, I was not sure how to handle it. I simply copied the way it was done in the applyFilter functions... Any advice would be welcomed ;)

> - aggregate name should be highlighted when hovered

It will be handle in the settings popup.

> - popup is not aligned with anything and its style is different from the filter popup (all popups should have the same style)

idem.

**Comment by katherdx** [comment]
@ValentinH Can you share aggregateFunc code that is Change the aggregateFunc of a data from the UI ?

**Comment by katherdx** [comment]
@ValentinH Can you share aggregateFunc code that is Change the aggregateFunc of a data from the UI ?

**Comment by ValentinH** [comment]
The code is the one in this pull request

**Comment by katherdx** [comment]
@ValentinH  thanks for response,  just now I am  download orb.js but I cant find new changes.  can you send to my email? katherjmc@gmail.com

**Comment by ValentinH** [comment]
As I said my changes are in this PR, look in the file tab: https://github.com/nnajm/orb/pull/15/files

**Comment by katherdx** [comment]
@ValentinH  Can you send me workable solution, please help me.

**Comment by ValentinH** [comment]
No

**Comment by katherdx** [comment]
Sorry I am asked demo orb.js with select the aggregation function from UI.

**Comment by katherdx** [comment]
I have one more question, did you implement lazy loading on orb on  ??

**Comment by ValentinH** [comment]
The code is in this PR. If you want me to do your job, then I'm available as a freelance and can invoice you. ;)

**Pull request closed without merging**
