### PR TITLE
Fix #19

### LINKED ISSUE #19: Drill down: empty grid when data source is an array of objects

### LINKED ISSUE #20: Drill-down not working with Array of objects
In the example, the drill-down works correctly but in my case, I use a datasource which consists in an array of objects and the drill-down grid is always empty.

I have noticed that [this line](https://github.com/nnajm/orb/blob/master/src/js/react/orb.react.Grid.jsx#L26) is the source of the problem because it iterates on data[i].length while data[i] is an object.

If I replace it by: 
```js
for(var j in data[i]) {
```
it works for array of arrays and array of objects.

### PR DESCRIPTION
**Pull request by ValentinH**
It fixes #19 where Drill-down did not work if dataSource was an array of objects.

### CODE REVIEW

**Comment by nnajm** [comment]
Very good. The patch is missing compiled js (in dist/ and js/react/react.compiled). You can do it using gulp (I saw that you did it in the previous PR). The build also runs some tests. Right now I'm working on the v1.0.9 branch, if you could submit your patches to that branch. Once stable, it will be merged with the master branch and released.

Thanks,

**Comment by ValentinH** [comment]
I think the reason is because I created this patch directly from the github website. I'll do it from my computer...

**Comment by ValentinH** [comment]
Actually, you already patched it in the 1.0.9 branch and in a cleaner way I did. This PR can be closed then.

**Comment by ValentinH** [comment]
BTW what will be the new features in 1.0.9?

**Comment by nnajm** [comment]
new option: **canMoveFields**: whether or not fields can move between areas. (done)
new feature: **Ctrl+Click** on a field button will expand/collapse all its values. (done)
working on: export to excel+csv

+ fixes for all identified bugs (done)

that will be the 1.0.9 release.

**Comment by ValentinH** [comment]
Cool :)

**Pull request closed without merging**
